PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX spc: <http://data.safepec.eu/2016/bn/0.2/>
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Competency Question 6:
# Which expert_table gives the state_values for a given bn_node?
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SELECT DISTINCT ?bn_node_class ?state_class ?table
WHERE 
{
  VALUES ?bn_node_class { spc:class_corr_nd } .
  #
  ?state_class owl:equivalentClass|rdfs:subClassOf ?a .
  ?a owl:intersectionOf*/(rdf:rest*/rdf:first)* ?restriction .
  ?restriction rdf:type owl:Restriction .
  ?restriction owl:onProperty ?on_property .
  ?restriction owl:someValuesFrom|owl:allValuesFrom ?bn_node_class .
  FILTER ( ?on_property = spc:appliesTo ) .
  OPTIONAL{ ?state_class spc:providedByTable ?table . } .
}
