PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX spc: <http://data.safepec.eu/2016/bn/0.2/>
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Competency Question 7:
# Which lookup_parameters (class) encode the state (class) or cpd_parameters (class) on the expert_table?
# (expert_table is closely related to bn_node and thus substituted by bn_node in this test.)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SELECT DISTINCT ?state_class ?lookup_param_class ?table
WHERE 
{
  # VALUES ?state_class { spc:iacs_class_lookup_param } .
  #
  ?state_class owl:equivalentClass|rdfs:subClassOf ?a .
  ?a owl:intersectionOf*/(rdf:rest*/rdf:first)* ?restriction .
  ?restriction rdf:type owl:Restriction .
  ?restriction owl:onProperty ?on_property .
  ?restriction owl:someValuesFrom|owl:allValuesFrom ?lookup_param_class .
  FILTER ( ?on_property = spc:dependsOn ) .
  OPTIONAL{ ?state_class spc:providedByTable ?table . } .
}
