PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dc: <http://xmlns.com/foaf/0.1/>
PREFIX : <http://xmlns.com/foaf/0.1/>
PREFIX dbpedia2: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Queries to DBPedia by http://dbpedia.org/snorql
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Learn, what the dbpedia property "shipRegistry" is about.
# ~> dbpedia2:shipRegistry is a (data) property and denotes the port of registry
# the port of registry is either given as a string or a URI of the city.
# there are also results for which the shipRegistry is a year date.
# for one subject there may be more than one dbpedia2:shipRegistry results. This
# gives an indication, that the ship changed flag. but there is no evidence about
# the current port of registry.
SELECT * WHERE {
 ?a <http://dbpedia.org/property/shipRegistry> ?b .
} LIMIT 100
#
#
# Learn, what a dbpedia.ontology/Ship is about. and how dbpedia2.shipIdentification works.
SELECT DISTINCT * WHERE {
  ?vessel rdf:type <http://dbpedia.org/ontology/Ship> .
  ?vessel dbpedia2:shipIdentification ?imoNumber .
} LIMIT 100


SELECT DISTINCT * WHERE {
  ?vessel rdf:type <http://dbpedia.org/ontology/Ship> .
  ?vessel dbpedia2:shipIdentification ?shipId.
  ?vessel ?prop ?obj .
  FILTER regex(str(?shipId), "9173317", "i")
} LIMIT 100
